package com.contract.management.domain.model;

import com.contract.management.domain.model.valueobject.OperationDetails;
import com.contract.management.domain.model.valueobject.OperationLogId;
import com.contract.management.domain.model.valueobject.OperationType;
import com.contract.management.domain.model.valueobject.ResourceType;
import lombok.Getter;

import java.time.LocalDateTime;
import java.util.Map;
import java.util.Objects;

/**
 * 操作日志聚合根
 *
 * @author SaltyFish
 * @since 1.0.0
 */
@Getter
public class OperationLog {

    private final OperationLogId id;
    private final OperationType operationType;
    private final ResourceType resourceType;
    private final Long resourceId;
    private final OperationDetails operationDetails;
    private final Long userId;
    private final String ipAddress;
    private final String userAgent;
    private final Long executionTimeMs;
    private final LocalDateTime createdTime;

    /**
     * 构造函数 - 创建新的操作日志
     */
    public OperationLog(OperationLogId id, OperationType operationType, ResourceType resourceType,
                       Long resourceId, OperationDetails operationDetails, Long userId,
                       String ipAddress, String userAgent, Long executionTimeMs) {
        this.id = id;
        this.operationType = operationType;
        this.resourceType = resourceType;
        this.resourceId = resourceId;
        this.operationDetails = operationDetails;
        this.userId = userId;
        this.ipAddress = ipAddress;
        this.userAgent = userAgent;
        this.executionTimeMs = executionTimeMs;
        this.createdTime = LocalDateTime.now();

        // 验证业务规则
        validate();
    }

    /**
     * 构造函数 - 从数据库重建
     */
    public OperationLog(OperationLogId id, OperationType operationType, ResourceType resourceType,
                       Long resourceId, OperationDetails operationDetails, Long userId,
                       String ipAddress, String userAgent, Long executionTimeMs,
                       LocalDateTime createdTime) {
        this.id = id;
        this.operationType = operationType;
        this.resourceType = resourceType;
        this.resourceId = resourceId;
        this.operationDetails = operationDetails;
        this.userId = userId;
        this.ipAddress = ipAddress;
        this.userAgent = userAgent;
        this.executionTimeMs = executionTimeMs;
        this.createdTime = createdTime;
    }

    // ==================== 业务规则验证 ====================

    /**
     * 验证操作日志的业务规则
     */
    private void validate() {
        if (operationType == null) {
            throw new IllegalArgumentException("操作类型不能为空");
        }
        if (resourceType == null) {
            throw new IllegalArgumentException("资源类型不能为空");
        }
        if (userId == null || userId <= 0) {
            throw new IllegalArgumentException("用户ID必须是正数");
        }
        if (operationDetails == null) {
            throw new IllegalArgumentException("操作详情不能为空");
        }
    }

    // ==================== 领域行为方法 ====================

    /**
     * 检查是否为条款抽取相关的操作
     */
    public boolean isClauseExtractionOperation() {
        return resourceType == ResourceType.CLAUSE_EXTRACTION;
    }

    /**
     * 检查是否为合同相关的操作
     */
    public boolean isContractOperation() {
        return resourceType == ResourceType.CONTRACT;
    }

    /**
     * 检查是否为成功操作
     */
    public boolean isSuccessOperation() {
        return "SUCCESS".equals(operationDetails.getResult());
    }

    /**
     * 检查是否为失败操作
     */
    public boolean isFailureOperation() {
        return "FAILURE".equals(operationDetails.getResult());
    }

    /**
     * 检查是否为进行中操作
     */
    public boolean isInProgressOperation() {
        return "IN_PROGRESS".equals(operationDetails.getResult());
    }

    // ==================== 静态工厂方法 ====================

    /**
     * 创建条款抽取开始日志
     */
    public static OperationLog createClauseExtractionStart(Long extractionId, Long contractId,
                                                         Long userId, String ipAddress) {
        OperationDetails details = OperationDetails.inProgress("开始条款抽取任务");
        details.setParameters(Map.of(
            "extractionId", extractionId,
            "contractId", contractId
        ));

        return new OperationLog(
            null, // ID will be generated by database
            OperationType.CLAUSE_EXTRACTION_START,
            ResourceType.CLAUSE_EXTRACTION,
            extractionId,
            details,
            userId,
            ipAddress,
            null,
            null
        );
    }

    /**
     * 创建条款抽取成功日志
     */
    public static OperationLog createClauseExtractionSuccess(Long extractionId, Long contractId,
                                                           Long userId, String ipAddress,
                                                           Long executionTimeMs,
                                                           String resultSummary) {
        OperationDetails details = OperationDetails.success("条款抽取任务完成");
        details.setParameters(Map.of(
            "extractionId", extractionId,
            "contractId", contractId
        ));
        details.setResult(resultSummary);

        return new OperationLog(
            null, // ID will be generated by database
            OperationType.CLAUSE_EXTRACTION_SUCCESS,
            ResourceType.CLAUSE_EXTRACTION,
            extractionId,
            details,
            userId,
            ipAddress,
            null,
            executionTimeMs
        );
    }

    /**
     * 创建条款抽取失败日志
     */
    public static OperationLog createClauseExtractionFailure(Long extractionId, Long contractId,
                                                           Long userId, String ipAddress,
                                                           Long executionTimeMs,
                                                           String errorMessage) {
        OperationDetails details = OperationDetails.failure("条款抽取任务失败", errorMessage);
        details.setParameters(Map.of(
            "extractionId", extractionId,
            "contractId", contractId
        ));

        return new OperationLog(
            null, // ID will be generated by database
            OperationType.CLAUSE_EXTRACTION_FAILED,
            ResourceType.CLAUSE_EXTRACTION,
            extractionId,
            details,
            userId,
            ipAddress,
            null,
            executionTimeMs
        );
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        OperationLog that = (OperationLog) o;

        // 如果两个对象都有ID，使用ID比较（已持久化的对象）
        if (id != null && that.id != null) {
            return id.equals(that.id);
        }

        // 如果两个对象都没有ID，使用业务属性比较（未持久化的对象）
        if (id == null && that.id == null) {
            return Objects.equals(operationType, that.operationType) &&
                   Objects.equals(resourceType, that.resourceType) &&
                   Objects.equals(resourceId, that.resourceId) &&
                   Objects.equals(userId, that.userId) &&
                   Objects.equals(createdTime, that.createdTime);
        }

        // 一个有ID一个没有ID，不相等
        return false;
    }

    @Override
    public int hashCode() {
        if (id != null) {
            return id.hashCode();
        }

        // 对于未持久化的对象，使用业务属性生成哈希码
        return Objects.hash(
            operationType,
            resourceType,
            resourceId,
            userId,
            createdTime
        );
    }

    @Override
    public String toString() {
        return "OperationLog{" +
                "id=" + id +
                ", operationType=" + operationType +
                ", resourceType=" + resourceType +
                ", resourceId=" + resourceId +
                ", userId=" + userId +
                ", result=" + operationDetails.getResult() +
                ", createdTime=" + createdTime +
                '}';
    }
}