-- ============================================================================
-- V1: Core Base Tables
-- 核心基础表（无外部依赖）
-- 包含：contract, task, file, operation_log, prompt, contract_review_rule
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. 共用函数和触发器
-- ----------------------------------------------------------------------------

-- 创建更新时间自动更新的触发器函数
CREATE OR REPLACE FUNCTION update_updated_time_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_time = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- ----------------------------------------------------------------------------
-- 2. 合同主表 (contract)
-- ----------------------------------------------------------------------------
CREATE TABLE contract (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_name VARCHAR(255) NOT NULL,
    contract_type VARCHAR(50),
    party_a_name VARCHAR(255),
    party_a_contact VARCHAR(255),
    party_a_address TEXT,
    party_b_name VARCHAR(255),
    party_b_contact VARCHAR(255),
    party_b_address TEXT,
    contract_amount DECIMAL(15,2),
    sign_date DATE,
    effective_date DATE,
    expiry_date DATE,
    attachment_uuid VARCHAR(64),
    description TEXT,
    created_by BIGINT NOT NULL,
    updated_by BIGINT NOT NULL,
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    object_version_number BIGINT DEFAULT 0,
    is_deleted BOOLEAN DEFAULT FALSE,

    -- 约束
    CONSTRAINT chk_contract_amount_positive CHECK (contract_amount IS NULL OR contract_amount >= 0),
    CONSTRAINT chk_contract_dates CHECK (
        (sign_date IS NULL OR effective_date IS NULL OR effective_date >= sign_date) AND
        (effective_date IS NULL OR expiry_date IS NULL OR expiry_date >= effective_date)
    )
);

-- 创建索引
CREATE INDEX idx_contract_type ON contract(contract_type);
CREATE INDEX idx_contract_created_by ON contract(created_by);
CREATE INDEX idx_contract_created_time ON contract(created_time);
CREATE INDEX idx_contract_is_deleted ON contract(is_deleted);
CREATE INDEX idx_contract_expiry_date ON contract(expiry_date);
CREATE INDEX idx_contract_attachment_uuid ON contract(attachment_uuid);

-- 创建唯一约束（同一创建人不能有重复的合同名称，排除已删除的记录）
CREATE UNIQUE INDEX uk_contract_name_creator ON contract(contract_name, created_by)
WHERE is_deleted = true;

-- 添加注释
COMMENT ON TABLE contract IS '合同主表';
COMMENT ON COLUMN contract.id IS '合同唯一标识';
COMMENT ON COLUMN contract.contract_name IS '合同名称';
COMMENT ON COLUMN contract.contract_type IS '合同类型：SALES, PURCHASE, SERVICE, LEASE, EMPLOYMENT, OTHER';
COMMENT ON COLUMN contract.party_a_name IS '甲方名称';
COMMENT ON COLUMN contract.party_a_contact IS '甲方联系方式';
COMMENT ON COLUMN contract.party_a_address IS '甲方地址';
COMMENT ON COLUMN contract.party_b_name IS '乙方名称';
COMMENT ON COLUMN contract.party_b_contact IS '乙方联系方式';
COMMENT ON COLUMN contract.party_b_address IS '乙方地址';
COMMENT ON COLUMN contract.contract_amount IS '合同金额';
COMMENT ON COLUMN contract.sign_date IS '签署日期';
COMMENT ON COLUMN contract.effective_date IS '生效日期';
COMMENT ON COLUMN contract.expiry_date IS '到期日期';
COMMENT ON COLUMN contract.attachment_uuid IS '附件UUID引用';
COMMENT ON COLUMN contract.description IS '合同描述';
COMMENT ON COLUMN contract.created_by IS '创建人ID';
COMMENT ON COLUMN contract.created_time IS '创建时间';
COMMENT ON COLUMN contract.updated_time IS '更新时间';
COMMENT ON COLUMN contract.is_deleted IS '是否删除';

-- 为合同表添加更新时间触发器
CREATE TRIGGER update_contract_updated_time
    BEFORE UPDATE ON contract
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_time_column();

-- ----------------------------------------------------------------------------
-- 3. 任务基础表 (task)
-- ----------------------------------------------------------------------------
CREATE TABLE task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_name VARCHAR(255) NOT NULL,
    task_status VARCHAR(50) NOT NULL,
    current_stage VARCHAR(50) DEFAULT 'PENDING',
    task_type VARCHAR(50) NOT NULL,
    error_message TEXT,
    created_by BIGINT NOT NULL,
    updated_by BIGINT NOT NULL,
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    object_version_number BIGINT DEFAULT 0,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    configuration JSONB DEFAULT '{}'
);

-- 创建索引
CREATE INDEX idx_task_status ON task(task_status);
CREATE INDEX idx_task_type ON task(task_type);
CREATE INDEX idx_task_created_by ON task(created_by);
CREATE INDEX idx_task_created_time ON task(created_time);
CREATE INDEX idx_task_started_time ON task(start_time);

-- 创建更新时间触发器（重用已创建的函数）
CREATE TRIGGER update_task_updated_time
    BEFORE UPDATE ON task
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_time_column();

-- 添加注释
COMMENT ON TABLE task IS '任务基础表';
COMMENT ON COLUMN task.id IS '任务ID';
COMMENT ON COLUMN task.task_name IS '任务名称';
COMMENT ON COLUMN task.task_status IS '任务状态';
COMMENT ON COLUMN task.current_stage IS '当前阶段';
COMMENT ON COLUMN task.task_type IS '任务类型';
COMMENT ON COLUMN task.error_message IS '错误信息';
COMMENT ON COLUMN task.created_by IS '创建人ID';
COMMENT ON COLUMN task.updated_by IS '更新人ID';
COMMENT ON COLUMN task.created_time IS '创建时间';
COMMENT ON COLUMN task.updated_time IS '更新时间';
COMMENT ON COLUMN task.object_version_number IS '对象版本号';
COMMENT ON COLUMN task.start_time IS '开始时间';
COMMENT ON COLUMN task.end_time IS '结束时间';
COMMENT ON COLUMN task.configuration IS '任务配置，JSON格式';

-- ----------------------------------------------------------------------------
-- 4. 文件信息表 (file)
-- ----------------------------------------------------------------------------
CREATE TABLE file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attachment_uuid VARCHAR(50),
    directory VARCHAR(400),
    file_url VARCHAR(120),
    file_type VARCHAR(240),
    file_name VARCHAR(240),
    file_size BIGINT,
    bucket_name VARCHAR(60),
    source_type VARCHAR(60),
    is_encrypted BOOLEAN DEFAULT FALSE,
    encryption_algorithm VARCHAR(20),
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 创建索引提高查询性能
CREATE INDEX idx_file_attachment_uuid ON file(attachment_uuid);
CREATE INDEX idx_file_bucket_name ON file(bucket_name);

-- 添加注释
COMMENT ON TABLE file IS '文件信息表';
COMMENT ON COLUMN file.id IS '主键，自增ID';
COMMENT ON COLUMN file.attachment_uuid IS '附件UUID';
COMMENT ON COLUMN file.directory IS '文件目录';
COMMENT ON COLUMN file.file_url IS '文件URL';
COMMENT ON COLUMN file.file_type IS '文件类型';
COMMENT ON COLUMN file.file_name IS '文件名称';
COMMENT ON COLUMN file.file_size IS '文件大小()';
COMMENT ON COLUMN file.bucket_name IS 'Bucket名称';
COMMENT ON COLUMN file.source_type IS '来源类型';
COMMENT ON COLUMN file.is_encrypted IS '是否加密';
COMMENT ON COLUMN file.encryption_algorithm IS '加密算法';

-- 创建更新时间触发器（重用已创建的函数）
CREATE TRIGGER update_file_updated_time BEFORE UPDATE
    ON file FOR EACH ROW EXECUTE FUNCTION update_updated_time_column();

-- ----------------------------------------------------------------------------
-- 5. 操作日志表 (operation_log)
-- ----------------------------------------------------------------------------
CREATE TABLE operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_type VARCHAR(50) NOT NULL,
    resource_type VARCHAR(50) NOT NULL,
    resource_id BIGINT,
    operation_details JSONB,
    user_id BIGINT NOT NULL,
    ip_address VARCHAR(45),
    user_agent TEXT,
    execution_time_ms BIGINT,
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 创建索引
CREATE INDEX idx_operation_log_user_id ON operation_log(user_id);
CREATE INDEX idx_operation_log_resource ON operation_log(resource_type, resource_id);
CREATE INDEX idx_operation_log_created_time ON operation_log(created_time);
CREATE INDEX idx_operation_log_operation_type ON operation_log(operation_type);

-- 添加注释
COMMENT ON TABLE operation_log IS '操作日志表';
COMMENT ON COLUMN operation_log.id IS '日志ID';
COMMENT ON COLUMN operation_log.operation_type IS '操作类型';
COMMENT ON COLUMN operation_log.resource_type IS '资源类型';
COMMENT ON COLUMN operation_log.resource_id IS '资源ID';
COMMENT ON COLUMN operation_log.operation_details IS '操作详情，JSON格式';
COMMENT ON COLUMN operation_log.user_id IS '用户ID';
COMMENT ON COLUMN operation_log.ip_address IS 'IP地址';
COMMENT ON COLUMN operation_log.user_agent IS '用户代理';
COMMENT ON COLUMN operation_log.execution_time_ms IS '执行时间(毫秒)';
COMMENT ON COLUMN operation_log.created_time IS '创建时间';

-- ----------------------------------------------------------------------------
-- 6. 提示词模板表 (prompt)
-- ----------------------------------------------------------------------------
CREATE TABLE prompt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prompt_name VARCHAR(120) NOT NULL,
    prompt_type VARCHAR(30) NOT NULL CHECK (prompt_type IN ('INNER', 'CUSTOM')),
    prompt_role VARCHAR(30) NOT NULL CHECK (prompt_role IN ('SYSTEM', 'USER', 'ASSISTANT')),
    prompt_content TEXT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    response_format VARCHAR(30),
    remark VARCHAR(600),
    created_by BIGINT NOT NULL,
    updated_by BIGINT NOT NULL DEFAULT -1,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    object_version_number BIGINT NOT NULL DEFAULT 0
);

-- 创建索引
CREATE INDEX idx_prompt_type ON prompt(prompt_type);
CREATE INDEX idx_prompt_enabled ON prompt(enabled);
CREATE INDEX idx_prompt_created_by ON prompt(created_by);
CREATE INDEX idx_prompt_created_time ON prompt(created_time);
CREATE INDEX idx_prompt_role ON prompt(prompt_role);
CREATE INDEX idx_prompt_response_format ON prompt(response_format);

-- 创建唯一约束（同一类型下启用的模板名称唯一）
CREATE UNIQUE INDEX uk_prompt_name_type ON prompt(prompt_name, prompt_type) WHERE enabled = true;

-- 添加注释
COMMENT ON TABLE prompt IS '提示词模板表';
COMMENT ON COLUMN prompt.id IS '主键ID';
COMMENT ON COLUMN prompt.prompt_name IS '模板名称';
COMMENT ON COLUMN prompt.prompt_type IS '模板类型：INNER-系统内置,CUSTOM-用户自定义';
COMMENT ON COLUMN prompt.prompt_role IS '角色类型：SYSTEM-系统,USER-用户,ASSISTANT-助手';
COMMENT ON COLUMN prompt.prompt_content IS '提示词内容';
COMMENT ON COLUMN prompt.enabled IS '是否启用';
COMMENT ON COLUMN prompt.response_format IS '响应格式：markdown,json等';
COMMENT ON COLUMN prompt.remark IS '描述备注';
COMMENT ON COLUMN prompt.created_by IS '创建人ID';
COMMENT ON COLUMN prompt.updated_by IS '更新人ID';
COMMENT ON COLUMN prompt.created_time IS '创建时间';
COMMENT ON COLUMN prompt.updated_time IS '更新时间';
COMMENT ON COLUMN prompt.object_version_number IS '行版本号，用于乐观锁';

-- 添加触发器，自动更新 updated_time 字段
CREATE TRIGGER trigger_update_prompt_updated_time
    BEFORE UPDATE ON prompt
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_time_column();

-- ----------------------------------------------------------------------------
-- 7. 合同审查规则表 (contract_review_rule)
-- ----------------------------------------------------------------------------

-- 创建规则类型枚举
CREATE TYPE rule_type_enum AS ENUM (
    'specific',    -- 专属规则（合同/条款类型专属）
    'fallback',    -- 兜底规则（所有合同通用）
    'extended'     -- 扩展规则（仅严格模式启用）
);

COMMENT ON TYPE rule_type_enum IS '规则类型枚举：specific=专属规则 fallback=兜底规则 extended=扩展规则';

-- 创建核心规则表
CREATE TABLE contract_review_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_name VARCHAR(255) NOT NULL,
    rule_type rule_type_enum NOT NULL,
    applicable_contract_type TEXT[] NOT NULL,
    applicable_clause_type TEXT[] NOT NULL,
    rule_content TEXT NOT NULL,
    prompt_mode_code SMALLINT NOT NULL CHECK (prompt_mode_code IN (0,1,2)),
    enabled BOOLEAN NOT NULL DEFAULT true,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    category VARCHAR(50),
    remark TEXT
);

-- 添加注释
COMMENT ON TABLE contract_review_rule IS '合同审查核心规则表';
COMMENT ON COLUMN contract_review_rule.id IS '规则主键ID';
COMMENT ON COLUMN contract_review_rule.rule_name IS '规则名称（简洁易懂，如"采购合同-质量异议期校验"）';
COMMENT ON COLUMN contract_review_rule.rule_type IS '规则类型：specific=专属规则 fallback=兜底规则 extended=扩展规则';
COMMENT ON COLUMN contract_review_rule.applicable_contract_type IS '适用合同类型（数组格式，兜底规则填["all"]）';
COMMENT ON COLUMN contract_review_rule.applicable_clause_type IS '适用条款类型（数组格式，如["付款条款","违约责任"]）';
COMMENT ON COLUMN contract_review_rule.rule_content IS '规则文本提示词（供AI审查的核心指令）';
COMMENT ON COLUMN contract_review_rule.prompt_mode_code IS '关联模式编码：0=效率 1=标准 2=严格';
COMMENT ON COLUMN contract_review_rule.enabled IS '规则启用状态：true=启用，false=禁用';
COMMENT ON COLUMN contract_review_rule.create_time IS '规则创建时间';
COMMENT ON COLUMN contract_review_rule.update_time IS '规则更新时间（修改时自动刷新）';
COMMENT ON COLUMN contract_review_rule.category IS '规则分类，引用ReviewTypeDetail枚举值';
COMMENT ON COLUMN contract_review_rule.remark IS '规则备注（提示词设计思路、法规依据等）';

-- 创建索引
CREATE INDEX idx_contract_type_mode_enabled ON contract_review_rule (applicable_contract_type, prompt_mode_code, enabled);
CREATE INDEX idx_rule_type_mode_code ON contract_review_rule (rule_type, prompt_mode_code);
CREATE INDEX idx_prompt_mode_enabled ON contract_review_rule (prompt_mode_code, enabled);

-- 触发器：自动更新update_time字段
CREATE OR REPLACE FUNCTION update_rule_time()
RETURNS TRIGGER AS $$
BEGIN
    NEW.update_time = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_rule_update_time
BEFORE UPDATE ON contract_review_rule
FOR EACH ROW EXECUTE FUNCTION update_rule_time();
