-- ============================================================================
-- V3: Contract Review Tables
-- 合同审查模块表（依赖 task 表）
-- 包含：contract_task, review_result, review_rule_results
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. 合同任务表 (contract_task)
-- 依赖: task
-- ----------------------------------------------------------------------------
CREATE TABLE contract_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    contract_id BIGINT NOT NULL,
    file_uuid VARCHAR(50) NOT NULL,
    business_tags VARCHAR(255),
    review_type VARCHAR(50),
    custom_selected_review_types JSONB,
    industry VARCHAR(50),
    currency VARCHAR(50),
    contract_type VARCHAR(50),
    type_confidence DECIMAL(5,2),
    review_rules TEXT,
    prompt_template VARCHAR(20),
    result_data JSONB,
    enable_terminology BOOLEAN DEFAULT false,

    -- 审计字段 (来自AuditInfo)
    created_by BIGINT,
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    object_version_number BIGINT DEFAULT 1,

    -- 外键约束
    CONSTRAINT fk_contract_task_id FOREIGN KEY (task_id) REFERENCES task(id) ON DELETE CASCADE
);

-- 创建索引
CREATE INDEX idx_contract_task_contract_id ON contract_task(contract_id);
CREATE INDEX idx_contract_task_review_type ON contract_task(review_type);

-- 为 contract_task 表的 task_id 添加唯一约束，确保与 task 表一对一对应
ALTER TABLE contract_task ADD CONSTRAINT uk_contract_task_task_id UNIQUE (task_id);

-- 添加注释
COMMENT ON TABLE contract_task IS '合同审查任务表';
COMMENT ON COLUMN contract_task.id IS '主键ID';
COMMENT ON COLUMN contract_task.task_id IS '任务ID';
COMMENT ON COLUMN contract_task.contract_id IS '合同ID';
COMMENT ON COLUMN contract_task.file_uuid IS '文件UUID';
COMMENT ON COLUMN contract_task.business_tags IS '业务标签';
COMMENT ON COLUMN contract_task.review_type IS '审查类型';
COMMENT ON COLUMN contract_task.custom_selected_review_types IS '自定义选择的审查类型';
COMMENT ON COLUMN contract_task.industry IS '行业';
COMMENT ON COLUMN contract_task.currency IS '币种';
COMMENT ON COLUMN contract_task.contract_type IS '合同类型';
COMMENT ON COLUMN contract_task.type_confidence IS '类型置信度';
COMMENT ON COLUMN contract_task.review_rules IS '审查规则';
COMMENT ON COLUMN contract_task.prompt_template IS '提示模板';
COMMENT ON COLUMN contract_task.result_data IS '结果数据';
COMMENT ON COLUMN contract_task.enable_terminology IS '是否启用术语';
COMMENT ON COLUMN contract_task.created_by IS '创建人';
COMMENT ON COLUMN contract_task.created_time IS '创建时间';
COMMENT ON COLUMN contract_task.updated_by IS '更新人';
COMMENT ON COLUMN contract_task.updated_time IS '更新时间';
COMMENT ON COLUMN contract_task.object_version_number IS '对象版本号';
COMMENT ON CONSTRAINT uk_contract_task_task_id ON contract_task IS '合同任务表 task_id 唯一约束，确保与 task 表一对一关系';

-- 创建更新时间触发器
CREATE TRIGGER update_contract_task_updated_time
    BEFORE UPDATE ON contract_task
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_time_column();

-- ----------------------------------------------------------------------------
-- 2. 审查结果表 (review_result)
-- 依赖: task
-- ----------------------------------------------------------------------------
CREATE TABLE review_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    contract_id BIGINT NOT NULL,
    review_type VARCHAR(50) NOT NULL,
    overall_risk_level VARCHAR(20),
    summary TEXT,
    recommendations TEXT,
    risk_items JSONB,
    compliance_issues JSONB,
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- 阶段跟踪字段
    execution_stage VARCHAR(50),
    stage_status VARCHAR(50),
    processed_at TIMESTAMP DEFAULT NOW(),
    stage_result TEXT,

    -- 关键点字段
    key_points JSONB,

    -- 模型版本
    model_version VARCHAR(50),

    -- 证据列表
    evidences JSONB,

    -- 外键约束
    CONSTRAINT fk_review_result_task_id FOREIGN KEY (task_id) REFERENCES task(id) ON DELETE CASCADE
);

-- 创建索引
CREATE INDEX idx_review_result_task_id ON review_result(task_id);
CREATE INDEX idx_review_result_contract_id ON review_result(contract_id);
CREATE INDEX idx_review_result_review_type ON review_result(review_type);
CREATE INDEX idx_review_result_risk_level ON review_result(overall_risk_level);
CREATE INDEX idx_review_result_created_time ON review_result(created_time);
CREATE INDEX idx_review_result_stage ON review_result(execution_stage, stage_status);
CREATE INDEX idx_review_result_model_version ON review_result(model_version);
CREATE INDEX idx_review_result_evidences_gin ON review_result USING GIN(evidences);

-- 添加注释
COMMENT ON TABLE review_result IS '审查结果表';
COMMENT ON COLUMN review_result.id IS '审查结果ID';
COMMENT ON COLUMN review_result.task_id IS '任务ID';
COMMENT ON COLUMN review_result.contract_id IS '合同ID';
COMMENT ON COLUMN review_result.review_type IS '审查类型';
COMMENT ON COLUMN review_result.overall_risk_level IS '整体风险等级';
COMMENT ON COLUMN review_result.summary IS '审查摘要';
COMMENT ON COLUMN review_result.recommendations IS '建议意见';
COMMENT ON COLUMN review_result.risk_items IS '风险项，引用RiskItem对象列表，JSON格式';
COMMENT ON COLUMN review_result.compliance_issues IS '合规问题，JSON格式';
COMMENT ON COLUMN review_result.created_time IS '创建时间';
COMMENT ON COLUMN review_result.execution_stage IS '执行阶段，对应ExecutionStage枚举';
COMMENT ON COLUMN review_result.stage_status IS '阶段状态，对应TaskStatus枚举';
COMMENT ON COLUMN review_result.processed_at IS '阶段处理时间';
COMMENT ON COLUMN review_result.stage_result IS '阶段处理原始AI结果，TEXT格式存储大量文本数据';
COMMENT ON COLUMN review_result.key_points IS '关键点列表，包含关键点和修复建议';
COMMENT ON COLUMN review_result.model_version IS 'AI模型版本号，用于标识执行审查时使用的模型版本';
COMMENT ON COLUMN review_result.evidences IS '证据列表（JSON格式），存储审查过程中使用的证据信息';

-- ----------------------------------------------------------------------------
-- 3. 审查规则结果表 (review_rule_results)
-- 依赖: review_result
-- ----------------------------------------------------------------------------
CREATE TABLE review_rule_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_result_id BIGINT NOT NULL,
    risk_name VARCHAR(255) NOT NULL,
    rule_type VARCHAR(100) NOT NULL,
    risk_level VARCHAR(50) NOT NULL,
    risk_score DECIMAL(5,2),
    summary TEXT,
    findings JSONB,
    recommendation JSONB,
    risk_clause_id VARCHAR(255),
    origin_contract_text TEXT,
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- 外键约束
    CONSTRAINT fk_review_rule_results_review_result_id
        FOREIGN KEY (review_result_id) REFERENCES review_result(id) ON DELETE CASCADE
);

-- 创建索引
CREATE INDEX idx_review_rule_results_review_result_id ON review_rule_results(review_result_id);
CREATE INDEX idx_review_rule_results_risk_level ON review_rule_results(risk_level);
CREATE INDEX idx_review_rule_results_rule_type ON review_rule_results(rule_type);
CREATE INDEX idx_review_rule_results_risk_clause_id ON review_rule_results(risk_clause_id);

-- 添加注释
COMMENT ON TABLE review_rule_results IS '审查规则结果表，存储review_result中risk_items的详细内容';
COMMENT ON COLUMN review_rule_results.id IS '审查规则结果ID';
COMMENT ON COLUMN review_rule_results.review_result_id IS '关联的审查结果ID';
COMMENT ON COLUMN review_rule_results.risk_name IS '风险名称';
COMMENT ON COLUMN review_rule_results.rule_type IS '审查规则类型';
COMMENT ON COLUMN review_rule_results.risk_level IS '风险等级';
COMMENT ON COLUMN review_rule_results.risk_score IS '风险评分';
COMMENT ON COLUMN review_rule_results.summary IS '十字以内概要';
COMMENT ON COLUMN review_rule_results.findings IS '条款级别的结果';
COMMENT ON COLUMN review_rule_results.recommendation IS '操作建议';
COMMENT ON COLUMN review_rule_results.risk_clause_id IS '风险条款ID（字符串类型，可为空）';
COMMENT ON COLUMN review_rule_results.origin_contract_text IS '风险原文';
COMMENT ON COLUMN review_rule_results.created_time IS '创建时间';
