-- ============================================================================
-- V4: Clause Extraction Tables
-- 条款抽取模块表（依赖 contract 表）
-- 包含：clause_extractions, clause, document_structure, classification_result
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. 条款抽取状态表 (clause_extractions)
-- 依赖: contract
-- ----------------------------------------------------------------------------
CREATE TABLE clause_extractions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    error_message TEXT,
    extraction_result JSONB,
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    created_by BIGINT NOT NULL,
    updated_by BIGINT NOT NULL,
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    object_version_number BIGINT DEFAULT 0,
    is_deleted BOOLEAN DEFAULT FALSE,

    -- 外键约束
    CONSTRAINT fk_clause_extraction_contract_id FOREIGN KEY (contract_id) REFERENCES contract(id) ON DELETE CASCADE,

    -- 状态约束
    CONSTRAINT chk_clause_extraction_status CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED'))
);

-- 创建索引
CREATE INDEX idx_clause_extraction_contract_id ON clause_extractions(contract_id);
CREATE INDEX idx_clause_extraction_status ON clause_extractions(status);
CREATE INDEX idx_clause_extraction_started_at ON clause_extractions(started_at);
CREATE INDEX idx_clause_extraction_created_by ON clause_extractions(created_by);

-- 添加唯一约束 - 每个合同只能有一个活跃的抽取任务
CREATE UNIQUE INDEX idx_clause_extraction_unique_active ON clause_extractions(contract_id, is_deleted)
WHERE is_deleted = FALSE;

-- 添加触发器自动更新 updated_time
CREATE TRIGGER clause_extraction_updated_time_trigger
    BEFORE UPDATE ON clause_extractions
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_time_column();

-- 添加注释
COMMENT ON TABLE clause_extractions IS '条款抽取状态表，管理合同条款抽取任务的生命周期';
COMMENT ON COLUMN clause_extractions.id IS '条款抽取任务ID';
COMMENT ON COLUMN clause_extractions.contract_id IS '关联的合同ID';
COMMENT ON COLUMN clause_extractions.status IS '抽取状态：PENDING-待处理，PROCESSING-处理中，COMPLETED-已完成，FAILED-失败，CANCELLED-已取消';
COMMENT ON COLUMN clause_extractions.error_message IS '失败时的错误信息';
COMMENT ON COLUMN clause_extractions.extraction_result IS '抽取结果的JSON数据，包含条款详情、风险评估等';
COMMENT ON COLUMN clause_extractions.started_at IS '开始处理时间';
COMMENT ON COLUMN clause_extractions.completed_at IS '完成时间';
COMMENT ON COLUMN clause_extractions.created_by IS '创建人ID';
COMMENT ON COLUMN clause_extractions.updated_by IS '更新人ID';
COMMENT ON COLUMN clause_extractions.created_time IS '创建时间';
COMMENT ON COLUMN clause_extractions.updated_time IS '更新时间';
COMMENT ON COLUMN clause_extractions.object_version_number IS '对象版本号';
COMMENT ON COLUMN clause_extractions.is_deleted IS '是否删除';

-- ----------------------------------------------------------------------------
-- 2. 提取条款表 (clause)
-- 依赖: contract, clause_extractions
-- ----------------------------------------------------------------------------
CREATE TABLE clause (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT,
    contract_id BIGINT NOT NULL,
    clause_type VARCHAR(50) NOT NULL,
    clause_title VARCHAR(255),
    clause_content TEXT NOT NULL,
    clause_position JSONB,
    confidence_score DECIMAL(5,2),
    extracted_entities JSONB,
    risk_level VARCHAR(20),
    risk_factors JSONB,
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    object_version_number BIGINT DEFAULT 0,
    is_deleted BOOLEAN DEFAULT FALSE,
    extraction_task_id BIGINT,

    -- 外键约束
    CONSTRAINT fk_clause_contract_id FOREIGN KEY (contract_id) REFERENCES contract(id) ON DELETE CASCADE,
    CONSTRAINT fk_clause_extraction_task_id FOREIGN KEY (extraction_task_id) REFERENCES clause_extractions(id) ON DELETE CASCADE
);

-- 创建索引
CREATE INDEX idx_clause_contract_id ON clause(contract_id);
CREATE INDEX idx_clause_type ON clause(clause_type);
CREATE INDEX idx_clause_risk_level ON clause(risk_level);
CREATE INDEX idx_clause_created_time ON clause(created_time);
CREATE INDEX idx_clause_extracted_entities ON clause USING GIN(extracted_entities);
CREATE INDEX idx_clause_risk_factors ON clause USING GIN(risk_factors);
CREATE INDEX idx_clause_extraction_task_id ON clause(extraction_task_id);

-- 添加注释
COMMENT ON TABLE clause IS '提取条款表，存储从合同中提取的各类条款信息';
COMMENT ON COLUMN clause.id IS '条款ID';
COMMENT ON COLUMN clause.task_id IS '关联的条款抽取任务ID（已弃用，保留用于兼容性）';
COMMENT ON COLUMN clause.contract_id IS '关联的合同ID';
COMMENT ON COLUMN clause.clause_type IS '条款类型';
COMMENT ON COLUMN clause.clause_title IS '条款标题';
COMMENT ON COLUMN clause.clause_content IS '条款内容';
COMMENT ON COLUMN clause.clause_position IS '条款在文档中的位置信息，JSON格式';
COMMENT ON COLUMN clause.confidence_score IS '抽取置信度';
COMMENT ON COLUMN clause.extracted_entities IS '提取的实体信息，JSON格式';
COMMENT ON COLUMN clause.risk_level IS '风险等级：high/medium/low';
COMMENT ON COLUMN clause.risk_factors IS '风险因子，JSON格式';
COMMENT ON COLUMN clause.created_time IS '创建时间';
COMMENT ON COLUMN clause.object_version_number IS '乐观锁版本号';
COMMENT ON COLUMN clause.is_deleted IS '是否删除';
COMMENT ON COLUMN clause.extraction_task_id IS '关联的条款抽取任务ID，用于区分不同的抽取任务';

-- ----------------------------------------------------------------------------
-- 3. 文档结构表 (document_structure)
-- 依赖: contract, clause_extractions
-- ----------------------------------------------------------------------------
CREATE TABLE document_structure (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL,
    task_id BIGINT,
    total_pages INTEGER NOT NULL,
    document_type VARCHAR(100),
    parties JSONB,
    contract_date DATE,
    effective_date DATE,
    structure_info JSONB NOT NULL,
    special_areas JSONB,
    quality_metrics JSONB,
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- 外键约束
    CONSTRAINT fk_structure_contract_id FOREIGN KEY (contract_id) REFERENCES contract(id) ON DELETE CASCADE,
    CONSTRAINT fk_structure_task_id FOREIGN KEY (task_id) REFERENCES clause_extractions(id) ON DELETE SET NULL
);

-- 创建索引
CREATE INDEX idx_document_structure_contract_id ON document_structure(contract_id);
CREATE INDEX idx_document_structure_task_id ON document_structure(task_id);

-- 添加注释
COMMENT ON TABLE document_structure IS '文档结构表，存储合同文档的章节结构、页面信息和质量指标';
COMMENT ON COLUMN document_structure.id IS '文档结构ID';
COMMENT ON COLUMN document_structure.contract_id IS '关联的合同ID';
COMMENT ON COLUMN document_structure.task_id IS '关联的条款抽取任务ID';
COMMENT ON COLUMN document_structure.total_pages IS '文档总页数';
COMMENT ON COLUMN document_structure.document_type IS '文档类型识别结果';
COMMENT ON COLUMN document_structure.parties IS '合同双方信息，JSON格式';
COMMENT ON COLUMN document_structure.contract_date IS '合同签订日期';
COMMENT ON COLUMN document_structure.effective_date IS '合同生效日期';
COMMENT ON COLUMN document_structure.structure_info IS '章节结构信息，包含标题、页码、层级等';
COMMENT ON COLUMN document_structure.special_areas IS '特殊区域标记，如表格、签名区等';
COMMENT ON COLUMN document_structure.quality_metrics IS 'OCR和结构识别的质量指标';
COMMENT ON COLUMN document_structure.created_time IS '创建时间';

-- ----------------------------------------------------------------------------
-- 4. 合同分类结果表 (classification_result)
-- 依赖: contract
-- ----------------------------------------------------------------------------
CREATE TABLE classification_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL,
    contract_type VARCHAR(50) NOT NULL,
    classification_method VARCHAR(20) NOT NULL,
    confidence_score DECIMAL(5,4),
    model_version VARCHAR(50),
    classified_by BIGINT,
    classification_reason TEXT,
    metadata JSONB,
    is_active BOOLEAN DEFAULT TRUE,
    created_by BIGINT NOT NULL,
    updated_by BIGINT NOT NULL,
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    object_version_number BIGINT DEFAULT 0,
    is_deleted BOOLEAN DEFAULT FALSE,

    -- 外键约束
    CONSTRAINT fk_classification_contract FOREIGN KEY (contract_id) REFERENCES contract(id) ON DELETE CASCADE,

    -- 检查约束
    CONSTRAINT chk_confidence_score CHECK (confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)),
    CONSTRAINT chk_classification_method CHECK (classification_method IN ('AI', 'MANUAL', 'RULE_BASED'))
);

-- 创建索引
CREATE INDEX idx_classification_contract_id ON classification_result(contract_id);
CREATE INDEX idx_classification_contract_type ON classification_result(contract_type);
CREATE INDEX idx_classification_method ON classification_result(classification_method);
CREATE INDEX idx_classification_created_time ON classification_result(created_time);
CREATE INDEX idx_classification_is_active ON classification_result(is_active);
CREATE INDEX idx_classification_is_deleted ON classification_result(is_deleted);

-- 单独创建部分唯一索引
CREATE UNIQUE INDEX uk_classification_contract_active
ON classification_result(contract_id)
WHERE is_active = TRUE AND is_deleted = FALSE;

-- 创建更新时间触发器
CREATE TRIGGER update_classification_result_updated_time
    BEFORE UPDATE ON classification_result
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_time_column();

-- 添加注释
COMMENT ON TABLE classification_result IS '合同分类结果表';
COMMENT ON COLUMN classification_result.id IS '分类结果唯一标识';
COMMENT ON COLUMN classification_result.contract_id IS '关联的合同ID';
COMMENT ON COLUMN classification_result.contract_type IS '分类结果：SALES, PURCHASE, SERVICE, LEASE, LABOR, TECHNICAL, EMPLOYMENT, OTHER';
COMMENT ON COLUMN classification_result.classification_method IS '分类方法：AI-人工智能, MANUAL-人工, RULE_BASED-规则';
COMMENT ON COLUMN classification_result.confidence_score IS '置信度分数(0-1)';
COMMENT ON COLUMN classification_result.model_version IS 'AI模型版本（仅AI分类时使用）';
COMMENT ON COLUMN classification_result.classified_by IS '分类操作人ID（人工分类时使用）';
COMMENT ON COLUMN classification_result.classification_reason IS '分类原因或依据';
COMMENT ON COLUMN classification_result.metadata IS '额外的分类元数据（JSON格式）';
COMMENT ON COLUMN classification_result.is_active IS '是否为当前有效的分类结果';
COMMENT ON COLUMN classification_result.created_by IS '创建人ID';
COMMENT ON COLUMN classification_result.updated_by IS '更新人ID';
COMMENT ON COLUMN classification_result.created_time IS '创建时间';
COMMENT ON COLUMN classification_result.updated_time IS '更新时间';
COMMENT ON COLUMN classification_result.object_version_number IS '对象版本号';
COMMENT ON COLUMN classification_result.is_deleted IS '是否删除';
