-- ============================================================================
-- V6: Gateway Tables
-- 网关服务表（Contract Gateway）
-- 包含：access_rules, url_mappings
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. 共用触发器函数（兼容写法，无语法错误）
-- ----------------------------------------------------------------------------

-- 删除已存在的触发器函数（如果有）
DROP FUNCTION IF EXISTS update_updated_time_column() CASCADE;
-- 创建更新时间自动更新的触发器函数
CREATE OR REPLACE FUNCTION update_updated_time_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ----------------------------------------------------------------------------
-- 2. 访问规则表 (access_rules)
-- ----------------------------------------------------------------------------

-- 创建规则类型枚举（兼容写法：先判断是否存在，不存在则创建）
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'rule_type_enum') THEN
        CREATE TYPE rule_type_enum AS ENUM ('whitelist', 'blacklist');
    END IF;
END $$;

-- 创建匹配类型枚举（兼容写法）
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'match_type_enum') THEN
        CREATE TYPE match_type_enum AS ENUM ('path', 'ip', 'user', 'method');
    END IF;
END $$;

-- 创建匹配模式枚举（兼容写法）
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'match_pattern_enum') THEN
        CREATE TYPE match_pattern_enum AS ENUM ('exact', 'prefix', 'wildcard', 'regex');
    END IF;
END $$;

-- 创建表（添加IF NOT EXISTS，避免重复创建报错；TIMESTAMP改为TIMESTAMPTZ支持时区）
CREATE TABLE IF NOT EXISTS access_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_name VARCHAR(255) NOT NULL,
    rule_type rule_type_enum NOT NULL,
    match_type match_type_enum NOT NULL,
    match_pattern match_pattern_enum NOT NULL,
    match_value VARCHAR(500) NOT NULL,
    priority INTEGER NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT true,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    -- 约束
    CONSTRAINT chk_access_rules_priority CHECK (priority >= 0),
    CONSTRAINT uk_access_rules_rule_name UNIQUE (rule_name)
);

-- 创建索引（添加IF NOT EXISTS）
CREATE INDEX IF NOT EXISTS idx_access_rules_rule_type ON access_rules(rule_type);
CREATE INDEX IF NOT EXISTS idx_access_rules_enabled ON access_rules(enabled);
CREATE INDEX IF NOT EXISTS idx_access_rules_priority ON access_rules(priority DESC);
CREATE INDEX IF NOT EXISTS idx_access_rules_match_type ON access_rules(match_type);
CREATE INDEX IF NOT EXISTS idx_access_rules_match_pattern ON access_rules(match_pattern);

-- 创建部分索引
CREATE INDEX IF NOT EXISTS idx_access_rules_enabled_priority ON access_rules(enabled, priority DESC) WHERE enabled = true;

-- 添加注释
COMMENT ON TABLE access_rules IS '访问控制规则表 - 用于网关黑白名单控制';
COMMENT ON COLUMN access_rules.id IS '规则唯一标识';
COMMENT ON COLUMN access_rules.rule_name IS '规则名称';
COMMENT ON COLUMN access_rules.rule_type IS '规则类型：whitelist-白名单, blacklist-黑名单';
COMMENT ON COLUMN access_rules.match_type IS '匹配类型：path-路径, ip-IP地址, user-用户, method-HTTP方法';
COMMENT ON COLUMN access_rules.match_pattern IS '匹配模式：exact-精确匹配, prefix-前缀匹配, wildcard-通配符, regex-正则表达式';
COMMENT ON COLUMN access_rules.match_value IS '匹配值（根据match_type和match_pattern的具体值）';
COMMENT ON COLUMN access_rules.priority IS '优先级，数值越大优先级越高';
COMMENT ON COLUMN access_rules.enabled IS '是否启用';
COMMENT ON COLUMN access_rules.description IS '规则描述';
COMMENT ON COLUMN access_rules.created_at IS '创建时间（带时区）';
COMMENT ON COLUMN access_rules.updated_at IS '更新时间（带时区）';

-- 创建触发器
DROP TRIGGER IF EXISTS update_access_rules_updated_at ON access_rules;
CREATE TRIGGER update_access_rules_updated_at
    BEFORE UPDATE ON access_rules
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_time_column();

-- ----------------------------------------------------------------------------
-- 3. URL映射表 (url_mappings)
-- ----------------------------------------------------------------------------

-- 创建映射类型枚举（兼容写法）
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mapping_type_enum') THEN
        CREATE TYPE mapping_type_enum AS ENUM ('rewrite', 'redirect', 'alias');
    END IF;
END $$;

-- 创建表
CREATE TABLE IF NOT EXISTS url_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mapping_name VARCHAR(255) NOT NULL,
    external_path VARCHAR(500) NOT NULL,
    internal_path VARCHAR(500) NOT NULL,
    target_service VARCHAR(255),
    mapping_type mapping_type_enum NOT NULL,
    priority INTEGER NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT true,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    -- 约束
    CONSTRAINT chk_url_mappings_priority CHECK (priority >= 0),
    CONSTRAINT uk_url_mappings_external_path UNIQUE (external_path),
    CONSTRAINT uk_url_mappings_mapping_name UNIQUE (mapping_name)
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_url_mappings_external_path ON url_mappings(external_path);
CREATE INDEX IF NOT EXISTS idx_url_mappings_target_service ON url_mappings(target_service);
CREATE INDEX IF NOT EXISTS idx_url_mappings_mapping_type ON url_mappings(mapping_type);
CREATE INDEX IF NOT EXISTS idx_url_mappings_enabled ON url_mappings(enabled);
CREATE INDEX IF NOT EXISTS idx_url_mappings_priority ON url_mappings(priority DESC);

-- 创建部分索引
CREATE INDEX IF NOT EXISTS idx_url_mappings_enabled_priority ON url_mappings(enabled, priority DESC) WHERE enabled = true;

-- 添加注释
COMMENT ON TABLE url_mappings IS 'URL映射表 - 用于外部路径到内部路径的转换';
COMMENT ON COLUMN url_mappings.id IS '映射唯一标识';
COMMENT ON COLUMN url_mappings.mapping_name IS '映射名称';
COMMENT ON COLUMN url_mappings.external_path IS '外部访问路径';
COMMENT ON COLUMN url_mappings.internal_path IS '内部实际路径';
COMMENT ON COLUMN url_mappings.target_service IS '目标服务名（可选，用于服务路由）';
COMMENT ON COLUMN url_mappings.mapping_type IS '映射类型：rewrite-路径重写, redirect-重定向, alias-别名';
COMMENT ON COLUMN url_mappings.priority IS '优先级，数值越大优先级越高';
COMMENT ON COLUMN url_mappings.enabled IS '是否启用';
COMMENT ON COLUMN url_mappings.description IS '映射描述';
COMMENT ON COLUMN url_mappings.created_at IS '创建时间（带时区）';
COMMENT ON COLUMN url_mappings.updated_at IS '更新时间（带时区）';

-- 创建触发器
DROP TRIGGER IF EXISTS update_url_mappings_updated_at ON url_mappings;
CREATE TRIGGER update_url_mappings_updated_at
    BEFORE UPDATE ON url_mappings
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_time_column();
